### ISSUE TITLE
Make "starting" and "loading" states for health check

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/sphinx-relay-wrapper#6]
<img width="865" alt="Screen Shot 2022-01-13 at 3 42 20 PM" src="https://user-images.githubusercontent.com/7445670/149413601-b5951ace-63ff-4e80-bdeb-67b591bdb345.png">

**Comment by elvece** [comment]
I solved this in btcpay by using a custom health check script to check how long the service has been alive before running the curl command (stdin is the duration the service has been up in ms):

```
check_web(){
    DURATION=$(</dev/stdin)
    if (($DURATION <= 30000 )); then 
        echo $DURATION
        exit 60
    else
        curl --silent --show-error --fail btcpayserver.embassy:23000
        RES=$?
        if test "$RES" != 0; then
            echo "Web interface is unreachable"
            exit 1
        fi
    fi
}

**Comment by ProofOfKeags** [comment]
How does "loading" differ from "starting" just for my understanding?

**Comment by chrisguida** [comment]
Loading allows you to output a message, while starting does not. Starting is currently used for when the central curl call itself is failing, so you know the service hasn't started yet. Loading is used for things like the bitcoind sync health check, where the call is returning, but the service is not fully usable.
